### ISSUE TITLE
CSS Browser Reset

### ISSUE THREAD

**Issue by lheagy** [ubcgif/geoscixyz#3]
firefox, chrome and explorer are rendering a few pages differently, messing with figure sizes. Can we include a call to a css browser reset in conf.py to fix this?

**Comment by rowanc1** [comment]
I am wondering if this is because you have defined an extra html page inside, with head and body etc. I am guessing that most browsers won't like this...?

I could take a look at this next week if @jokulhaup of @lheagy bring up the build process on their comps.

**Comment by lheagy** [comment]
@rowanc1
Quite likely. Phil showed me an example yesterday, I can show you this week (or check out the DC resistivity: measurements and data page)

**Comment by lheagy** [comment]
All calls to the old css style sheets have been removed, so it should be the same across all browsers. If anyone has time to check, feel free to close the issue if everything is working! If not, I will get to it this weekend
