### ISSUE TITLE
Chapter on foundations and physical properties

### ISSUE THREAD

**Issue by dougoldenburg** [ubcgif/geoscixyz#7]
The links for stepping through images and small movies don't work for me.

thibaut was preparing a section of physical properties. Is any of that hooked up?

**Comment by lheagy** [comment]
Which images / movies? Can you specify the path? 

Thibaut's physical properties section has not yet been merged onto master yet. You can view it though by checking out his branch (I can send you instructions).

**Comment by dougoldenburg** [comment]
For instance    (Geophysics Primer)
Figure 2: An example of how the distribution of a physical property (electrical conductivity in this case) can be measured to provide information about geologic materials. Click buttons to reveal

**Comment by lheagy** [comment]
Broken Apps:

[ ] Figure 2: http://gpg.geosci.xyz/en/latest/content/foundations/foundations_seeing_underground_primer.html
[ ] Figure 3: http://gpg.geosci.xyz/en/latest/content/foundations/foundations_seeing_underground_example.html
[ ] Figures 5,6: http://gpg.geosci.xyz/en/latest/content/foundations/foundations_seeing_underground_example.html

**Comment by lheagy** [comment]
Are there any more that were broken? If not, feel free to close the issue. The fixes have only been pushed to master (I will sync everyone else's branches later). There are a couple that could use some formatting to make them look better, but for now, they at least need to function!

**Comment by dougoldenburg** [comment]
All links now seem to be working. Thanks.
