### ISSUE TITLE
Organization of Foundations unit

### ISSUE THREAD

**Issue by lheagy** [ubcgif/geoscixyz#8]
i)                    begin with the material for Seeing Underground and put all sections under that heading as in the old GPG. 
ii)                   Next section:  Seven-step method (don’t need a separate section for summary of seven step method)
iii)                 Survey methods
iv)                 Physical properties
v)                  Other items (title name) This includes  (a) model types, (b) Inversion outline)

**Comment by lheagy** [comment]
The contents of "foundations_contents" should also be put in the index. (It doesn't really make sense to have a table of contents with a link to the contents of the chapter)

**Comment by dougoldenburg** [comment]
I think the only thing that's useful in the current Contents is the image. Otherwise it's the 7-step procedure which is already presented.

**Comment by lheagy** [comment]
it will update in a moment, but how is this? http://gpg.geosci.xyz/en/latest/content/foundations/index.html
